### ISSUE TITLE
Request for the database

### ISSUE THREAD

**Issue by lfrankkkkk** [nmduc/deep-ternary#3]
Thank you for reading!
I have recently read your paper  "Deep Learning Sparse Ternary Projections For Compressed Sensing of Images",which gives me great inspiration. I am wondering if you could kindly send me the dataset with 5 million patches. I promise they will be used only for research purposed.
Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by nmduc** [comment]
Hi, thanks for your interest. I have just sent the link to download the dataset to your email. 
Hope it's helpful for you.
